'use client';
import {useEffect,useRef,useState} from 'react';
import {Advisory} from './review';
import {adviceViewRow,latestAdviceView,type AdviceViewRow as AdviceRow,type LatestAdviceView as Latest} from '../../src/advice/view-contract';
type Changes={lines:string[];privateNotice:string;summary:{pending:number;acceptedChanges:number};conflicts:{field:string}[]};
export default function AdviceView({caseId,revision,materialVersion}:{caseId:string;revision:number;materialVersion:number}){
 const [latest,setLatest]=useState<Latest|null>(null),[selected,setSelected]=useState<AdviceRow|null>(null),[history,setHistory]=useState<AdviceRow[]>([]),[changes,setChanges]=useState<Changes|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const heading=useRef<HTMLHeadingElement>(null);
 async function api(path:string,body?:unknown){const r=await fetch(`/api/cases/${caseId}/advice${path}`,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw Object.assign(new Error(d.error),{status:r.status});return d;}
 async function show(id:string){setSelected(adviceViewRow.parse(await api(`/${id}`)));setChanges(await api(`/${id}/changes`));}
 async function load(){const state=latestAdviceView.parse(await api(''));setLatest(state);const rows=(await api('/history') as unknown[]).map(row=>adviceViewRow.parse(row));setHistory(rows);if(state.latest){await show(state.latest.id);if(!state.latest.stale&&rows.length>1)setChanges(await api(`/${rows[1].id}/changes`));}else{setSelected(null);setChanges(null);}}
 useEffect(()=>{void load().catch(()=>setMessage("We couldn't load advice. Try again."));},[caseId,revision,materialVersion]);
 async function generate(){if(!latest)return;setBusy(true);setMessage('');try{await api('',{expectedRevision:latest.revision,expectedMaterialVersion:latest.materialVersion});await load();setMessage('Updated advice ready.');setTimeout(()=>heading.current?.focus(),0);}catch(e){setMessage((e as {status?:number}).status===409?'Your case changed while we were preparing this advice. Nothing was saved. Try again.':"We couldn't get updated advice. Your case is unchanged. Try again.");await load();}finally{setBusy(false);}}
 async function toggle(includePrivateConstraints:boolean){if(!latest)return;setBusy(true);try{await api('/settings',{expectedRevision:latest.revision,expectedMaterialVersion:latest.materialVersion,includePrivateConstraints});await load();}catch{setMessage("We couldn't save this setting. Try again.");await load();}finally{setBusy(false);}}
 return <section aria-label="Test advice"><h2 ref={heading} tabIndex={-1}>Test advice, not real guidance</h2><p>This advice was produced by a test generator to check the app's workings. It is not negotiation guidance. Do not act on it.</p>
 {message&&<p role="status">{message}</p>}
 <label><input type="checkbox" disabled={busy||!latest} checked={latest?.includePrivateConstraints??false} onChange={e=>void toggle(e.target.checked)}/> Include private limits and alternatives in test advice</label><p>{latest?.includePrivateConstraints?'Private figures are included in this test advice. Nothing leaves the app.':'Private constraints are not used.'}</p>
 {selected?.stale&&<div role="status"><h3>This advice is out of date</h3>{!!changes?.summary.pending&&<p>{changes.summary.pending} suggested change(s) from your latest import are waiting for your review.</p>}{!!changes?.summary.acceptedChanges&&<p>You accepted {changes.summary.acceptedChanges} change(s) after this advice was written.</p>}{changes?.conflicts.map((c,i)=><p key={i}>Two sources disagree about {c.field} and it is unresolved.</p>)}<p>The points below may no longer match your case.</p></div>}
 {(!selected||selected.stale)&&<button disabled={busy||!latest} onClick={()=>void generate()}>{busy?'Getting updated advice…':'Get updated advice'}</button>}
 {!!changes?.summary.pending&&<><a href="#review-suggested-changes">Review suggested changes first</a><p>Advice uses accepted details only. Suggested changes are not used until you accept them.</p></>}
 {selected&&<>{selected.id!==latest?.latest?.id&&<p>This is earlier advice. It is kept for reference and may not match your case now.</p>}<p>{selected.stale?'Out of date':'This advice is up to date.'}</p><p>Advice based on your case as reviewed {new Date(selected.created_at).toLocaleString()}. {selected.snapshot?.assertions.length??0} accepted details used.</p>
 {changes&&<div><h3>What changed since the previous advice</h3>{changes.lines.map((line,i)=><Advisory key={i} text={line}/>)}</div>}
 <h3>For you only. Do not share</h3>{selected.content.claims.map((claim,i)=><article key={i}><Advisory text={claim.text}/><details><summary>Show the evidence behind each point</summary><p>Based on:</p>{claim.assertion_ids.map(id=><p key={id}>{selected.sourceLabels?.find(s=>s.id===selected.snapshot?.assertions.find(a=>a.id===id)?.source_id)?.label??'Manual entry'} says {selected.snapshot?.assertions.find(a=>a.id===id)?.field??'Reviewed detail'}</p>)}{claim.evidence_ids.map(id=><blockquote key={id}><Advisory text={selected.snapshot?.evidence.find(e=>e.id===id)?.quote??'Not known yet'}/></blockquote>)}</details></article>)}
 <div><h3>Draft you could send</h3>{selected.content.draft?<><p>Contains no private limits or alternatives. Check it before sending.</p><Advisory text={selected.content.draft}/></>:<p>No draft yet. Nothing private is included in drafts.</p>}</div></>}
 <h3>Earlier advice</h3>{history.length<2&&<p>No earlier advice yet. Earlier versions will be kept here.</p>}{history.map(row=><button key={row.id} disabled={busy} onClick={()=>void show(row.id)}>{new Date(row.created_at).toLocaleString()} · {row.stale?'Out of date':'Current'} · based on {row.accepted_detail_count??0} accepted details</button>)}
 </section>;
}
